<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY5DXcux\testsSN_Bundle_NotificationsBundle_Tests_SNNotificationsKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY5DXcux/testsSN_Bundle_NotificationsBundle_Tests_SNNotificationsKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerY5DXcux.legacy');

    return;
}

if (!\class_exists(testsSN_Bundle_NotificationsBundle_Tests_SNNotificationsKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerY5DXcux\testsSN_Bundle_NotificationsBundle_Tests_SNNotificationsKernelTestDebugContainer::class, testsSN_Bundle_NotificationsBundle_Tests_SNNotificationsKernelTestDebugContainer::class, false);
}

return new \ContainerY5DXcux\testsSN_Bundle_NotificationsBundle_Tests_SNNotificationsKernelTestDebugContainer([
    'container.build_hash' => 'Y5DXcux',
    'container.build_id' => 'caf3136b',
    'container.build_time' => 1568090572,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY5DXcux');
